analyzers:
  base:
    type: GenericAnalyzer
    path: Base
    startswith: base
    num_items: 6
    remove_prefix: base_
  lwa:
    type: GenericAnalyzer
    path: Lwa
    startswith: lwa
    num_items: 16
    remove_prefix: lwa_
  gripper:
    type: GenericAnalyzer
    path: Gripper
    startswith: gripper
    num_items: 16
    remove_prefix: gripper_
  pan_tilt:
    type: GenericAnalyzer
    path: Pan_tilt
    startswith: pan_tilt
    num_items: 16
    remove_prefix: pan_tilt_
