max_obstacle_height: 0.60 # assume something like an arm is mounted on top of the robot
robot_radius: 0.4 # distance a circular robot should be clear of the obstacle

# map_type: voxel # not specified, uses a 2D obstacle map
obstacle_layer:
  enabled: true
  max_obstacle_height: 0.6
  obstacle_range: 30.0 # trusted distance in filling in obstacles phase
  raytrace_range: 30.0 # trusted distance in clearing phase
  track_unknown_space: true #true needed for disabling global path planning through unknown space
  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: /laser_front/scan
    marking: true
    clearing: true
  
inflation_layer:
  enabled: true
  cost_scaling_factor: 15.0 # exponential rate at which the obstacle cost drops off (default: 10), see http://wiki.ros.org/costmap_2d/flat
  inflation_radius: 0.6 # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled: true

sonar_layer:
    topics: ['/Ultrasound/Sensor0', '/Ultrasound/Sensor1', '/Ultrasound/Sensor2', '/Ultrasound/Sensor3', '/Ultrasound/Sensor4', '/Ultrasound/Sensor5', '/Ultrasound/Sensor6', '/Ultrasound/Sensor7']
    no_readings_timeout: 1.0

