# Dynamic Window Approach
DWAPlannerROS:
  # velocity limits
  max_vel_x: 0.25
  min_vel_x: -0.25 # no backwards motion, only laser scanner used
  max_vel_y:  0.25
  min_vel_y:  -0.25
  max_trans_vel: 0.3  # choose slightly less than the base's capability
  min_trans_vel: 0.05 # this is the min trans velocity when there is negligible rotational velocity
  trans_stopped_vel: 0.01
  # Warning!
  # do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
  # are non-negligible and small in place rotational velocities will be created.
  max_rot_vel: 0.3
  min_rot_vel: 0.0  #absolute value!
  rot_stopped_vel: 0.1
  
  # acceleration limits
  acc_lim_x: 0.2
  acc_lim_theta: 0.2
  acc_lim_y: 0.2
  
  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false # xy and theta goal has to be considered
  
  # Forward Simulation Parameters
  sim_time: 1.0
  vx_samples: 5
  vy_samples: 5
  vtheta_samples: 30
  
  # Trajectory Scoring Parameters
  path_distance_bias: 10.0 # weighting for how much it should stick to the global path plan
  goal_distance_bias: 40.0 # wighting for how much it should attempt to reach its goal
  occdist_scale: 10.0 # weighting for how much the controller should avoid obstacles
  forward_point_distance: 0.5 # distance to the next scoring point
  stop_time_buffer: 0.2 # amount of time that the robot must stop before a collision in order for a trajectory to be considered valid in seconds 
  scaling_speed: 0.25 # absolute velocity at which to start scaling (increasing) the robot's footprint
  max_scaling_factor: 0.2 # how much to scale the robot's footprint when at speed.
  
  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 # how far to travel before resetting oscillation flags
  
  # Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: /odom
  
  holonomic_robot: true
  
