omnirob_robin:
  base:
    # Position Controllers ---------------------------------------
    x_position_controller:
      type: position_controllers/JointPositionController
      joint: base_x_joint
      pid: {p: 1.0}
      
    y_position_controller:
      type: position_controllers/JointPositionController
      joint: base_y_joint
      pid: {p: 1.0}
    
    yaw_position_controller:
      type: position_controllers/JointPositionController
      joint: base_yaw_joint
      pid: {p: 1.0}
