omnirob_robin:
  base:
    # Position Controllers ---------------------------------------
    x_position_controller:
      type: position_controllers/JointPositionController
      joint: base/x_joint
      pid: {p: 1.0}
      
    y_position_controller:
      type: position_controllers/JointPositionController
      joint: base/y_joint
      pid: {p: 1.0}
    
    yaw_position_controller:
      type: position_controllers/JointPositionController
      joint: base/yaw_joint
      pid: {p: 1.0}
