omnirob_robin:
  gripper:
    left_position_controller:
      type: position_controllers/JointPositionController
      joint: gripper/finger_left_joint
      pid: {p: 1.0, d: 1.0}
      
    right_position_controller:
      type: position_controllers/JointPositionController
      joint: gripper/finger_right_joint
      pid: {p: 1.0, d: 1.0}
