# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  gripper/finger_left_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  gripper/finger_right_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  lwa/joint_1:
    has_velocity_limits: true
    max_velocity: 0.218
    has_acceleration_limits: true
    max_acceleration: 0.8725
  lwa/joint_2:
    has_velocity_limits: true
    max_velocity: 0.218
    has_acceleration_limits: true
    max_acceleration: 0.8725
  lwa/joint_3:
    has_velocity_limits: true
    max_velocity: 0.209
    has_acceleration_limits: true
    max_acceleration: 0.825
  lwa/joint_4:
    has_velocity_limits: true
    max_velocity: 0.209
    has_acceleration_limits: true
    max_acceleration: 0.825
  lwa/joint_5:
    has_velocity_limits: true
    max_velocity: 0.218
    has_acceleration_limits: true
    max_acceleration: 0.8725
  lwa/joint_6:
    has_velocity_limits: true
    max_velocity: 0.218
    has_acceleration_limits: true
    max_acceleration: 0.8725
  lwa/joint_7:
    has_velocity_limits: true
    max_velocity: 0.4365
    has_acceleration_limits: true
    max_acceleration: 1.745
