controller_list:
 - name: /omnirob_robin/lwa/controller/
   action_ns: continuous_control
   type: FollowJointTrajectory
   default: true
   joints:
     - lwa/joint_1
     - lwa/joint_2
     - lwa/joint_3
     - lwa/joint_4
     - lwa/joint_5
     - lwa/joint_6
     - lwa/joint_7
